### ISSUE TITLE
Support custom check definition with YAML or other languages

### ISSUE THREAD

**Issue by Owen-Cummings** [tfsec/tfsec#523]
**Is your feature request related to a problem? Please describe.**
It would be a nice feature if there was an option to use various languages such as YAML when writing custom checks. The main selling point for YAML is how human readable it is in addition to supporting comments. Working with json has mainly been an issue because it doesn't support comments. This would be beneficial as currently the only way to add context within the check file is in the description field.

Having a more robust tfsec related file parser could be leveraged down the road when adding config files and other features. It's definitely a nice to have but not a need to have. 

**Describe the solution you'd like**
An update to `custom_rules.go` that supports various languages. Making it able to handle more than json would be a good way to expand possible use cases similar to how tfsec supports different forms of output.

**Describe alternatives you've considered**
Write checks in json. 

**Additional context**
Sample of what a rule in YAML would look like
```yaml
---
checks:
- code: CUS001
  description: Does things
  requiredTypes:
  - resource
  - data
  requiredLabels:
  - cool_resource
  - cool_data
  severity: WARNING
  matchSpec:
    name: neat_block
    action: isPresent
    subMatch:
      name: nice_value
      action: equals
      value: good
  errorMessage: your nice_value is not good
  relatedLinks:
  - very-cool-website.co.uk
```
