### ISSUE TITLE
regexMatches custom check doesn't work

### ISSUE THREAD

**Issue by robertstettner** [tfsec/tfsec#783]
**Describe the bug**
For some reason my regular expression custom check is breaking all my other custom checks, and I'm not sure why.

**To Reproduce**

Using this custom check:
```yaml
---
checks:
  - code: CUS001
    description: Check to warn that the S3 Bucket does not conform to the naming convention
    impact: By not conforming to the naming convention it will make finding the resources much harder, and prevent systems from classifying them when needed
    resolution: Use the naming convention for S3 Buckets - ${namespace}-${accountId}(-${awsRegion})?
    requiredTypes:
      - resource
    requiredLabels:
      - aws_s3_bucket
    severity: WARNING
    matchSpec:
      name: bucket
      action: regexMatches
      value: "^[a-z\-]*[0-9]{12}(-[a-z]{2}-[a-z]{4}-[0-9])?$"
    errorMessage: The bucket does not conform to the naming convention
```

and this Terraform:
```ruby
resource "aws_s3_bucket" "new_bucket" {
  bucket = "dfgdfg"

  versioning {
    enabled = true
  }

  logging {
    target_bucket = aws_s3_bucket.log_bucket.id
    target_prefix = "log/"
  }

  server_side_encryption_configuration {
    rule {
      apply_server_side_encryption_by_default {
        sse_algorithm = "aws:kms"
      }
    }
  }
}
```

**Expected behavior**
I expect an warning to show that the S3 bucket does not have the correct naming convention

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: macos

**Additional context**
Using latest version `v0.40.2`
