### ISSUE TITLE
I need to check that a project(repo) contains only certain resource types

### ISSUE THREAD

**Issue by marcterraform** [tfsec/tfsec#792]
Hi,

I need to ensure my observability project only contains the following resource types:

aws_cloudwatch_metric_alarm
aws_cloudwatch_dashboard
aws_sns_topic
null_resource

I came close with:
requiresPresence
The requiresPresence checks that the resource in name is also present in the Terraform code.

I also tried the reverse, checking for all resource types and not'ting in with predicateMatch, but no success.

Describe the solution you'd like - requiresOnlyPresence action that ensures that only the listed resource types are in all tf files

Describe alternatives you've considered - Python code is working, but prefer to use tfsec.

Additional context - a hook to external python tool would be nice

**Comment by owenrumney** [comment]
Hey @marcterraform - how does something like this sound?

This check would essentially touch every resource and ensure it is on the match spec. 

```
---
checks:
  - code: TypeLimit
    description: Ensure that only specific types are used
    requiredTypes: 
      - resource
    requiredLabels: 
      - "*"
    errorMessage: resource types not on the allowed list were identified
    matchSpec:
      action: ofType
      name: ofType
      value: 
      - aws_cloudwatch_metric_alarm
      - aws_cloudwatch_dashboard
      - aws_sns_topic
      - null_resource
    severity: WARNING
    ```

I've added the required custom check action in #793 - I'll leave it till you confirm this is the sort of thing you were after
